[package]
name = "dict-picker"
<<<<<<< HEAD
version = "0.1.4"
=======
version = "0.1.3"
>>>>>>> b9d8e5a (change version for pypi)
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dict_picker"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
